site_name: plumbum
site_description: A plumbing syntax for Python
site_author: Nehal Patel
repo_url: https://github.com/habemus-papadum/pdum_plumbum
repo_name: pdum_plumbum

theme:
  name: "material"
  palette:
    primary: blue grey


nav:
  - Home: index.md
  - Tutorial: tutorial.ipynb
  - API: reference.md

# If you'd like to specify a separate docs directory, you can do so here
docs_dir: docs

# Plugins to enable
plugins:
  - search
  - mkdocs-jupyter:
      execute: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: false
            members: true
            inherited_members: true
            filters:
              - "!^_"
